version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  picsaso.cyrhades.fr:
    image: anssi/fcsc2023-reverse-picasso:latest
    read_only: true
    ports:
      - ${PORT_SSH}:4000
